spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/jw_db
    username: user
    password: password
  jpa:
#    hibernate:
#      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql

jwt:
  access-secret: 'some-access-secret'
  refresh-secret: 'some-refresh-secret'